networks:
  bridge_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
services:
  avito-estate-parser:
    image: avito-estate-parser:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rod
    restart: on-failure
    env_file:
      - .env
    environment:
      DEVTOOLS_WEBSOCKET_URL: ${DEVTOOLS_WEBSOCKET_URL}
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
      SEQ_URL: ${SEQ_URL}
      SEQ_TOKEN: ${SEQ_TOKEN}
      ENVIRONMENT: ${ENVIRONMENT}
      BUNDEBUG: ${BUNDEBUG}
    networks:
      bridge_network:
        ipv4_address: 10.5.0.5

  rod:
    image: ghcr.io/go-rod/rod
    hostname: rod
    ports:
      - "7317:7317"
    networks:
      bridge_network:
        ipv4_address: 10.5.0.6
