volumes:
  seq_data:

services:
  avito-estate-parser:
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "40000:40000"
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE

#  seq:
#    image: datalust/seq:latest
#    ports:
#      - "5341:80"
#    environment:
#      ACCEPT_EULA: "Y"
#    restart: unless-stopped
#    volumes:
#      - seq_data:/data
#    networks:
#      bridge_network:
#        ipv4_address: 10.5.0.7