volumes:
  cache:

services:
  browserless:
    image: ghcr.io/browserless/chromium
    hostname: browserless
    environment:
      TOKEN: ${BROWSERLESS_TOKEN}
#      PORT: 3000
      TIMEOUT: 600000
#      QUEUED: 5
#      CONCURRENT: 5
#      DEBUG: -*
      DATA_DIR: /tmp
    restart: unless-stopped
    volumes:
      - cache:/tmp
    ports:
      - "3000:3000"

  avito:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - browserless
    restart: unless-stopped
    environment:
      BROWSERLESS_TOKEN: ${BROWSERLESS_TOKEN}