volumes:
  cache:

services:
  rod:
    image: ghcr.io/go-rod/rod
    hostname: rod
    ports:
      - "7317:7317"

  avito:
    image: avito:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rod
    restart: on-failure
    env_file:
      - .env_prod
    environment:
      DEVTOOLS_WEBSOCKET_URL: ${DEVTOOLS_WEBSOCKET_URL}
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
      SEQ_URL: ${SEQ_URL}
      SEQ_TOKEN: ${SEQ_TOKEN}
      ENVIRONMENT: ${ENVIRONMENT}
      BUNDEBUG: ${BUNDEBUG}